#!/bin/bash
read -s -p "Enter your password: " lol

echo "Which day would you like to read?"
select f in `ls ~/.entry`
do
    openssl enc -aes-256-cbc -k $lol -a -d -in ~/.entry/${f} | less
    break
done
