#!/bin/bash

if ! [[ -d ~/.entry ]];
then
	mkdir ~/.entry
fi


if [ $# -eq 0 ];
then
	/$(dirname "${BASH_SOURCE[0]}")/reader
else
	if [ "$@" == "w" ];
	then
		/$(dirname "${BASH_SOURCE[0]}")/writer
	fi
fi 
