#!/bin/bash

FILE=`date +"%Y"`
read -s -p "Enter your password: " lol

if [ -f ~/.entry/$FILE.txt ]
then
	openssl enc -aes-256-cbc -a -d -k "$lol" -in ~/.entry/${FILE}.txt -out thing.txt.tmp
fi
date +"%d/%m %H:%M" >> thing.txt.tmp && vim thing.txt.tmp && openssl enc -aes-256-cbc -a -k "$lol" -in thing.txt.tmp -out ~/.entry/${FILE}.txt && rm thing.txt.tmp
history -c
